plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141' 
}

version = '1.0.0'
group = 'com.valhyi.recyclertable'

base {
    archivesName = 'recyclertable'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    enable {
        version = '26.2.0.70'
        disableRecompilation = false
    }
    // ... el resto de tu bloque runs/mods igual
runs {
        client {
            client()
        }
    }
}
    mods {
        recyclertable {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
    mavenCentral()
}

dependencies {
    // Esto es lo que faltaba para obligar a Gradle a descargar el entorno de 26.2
    implementation "net.neoforged:neoforge:${neoForge.version}"
}
