plugins {
    id 'java-library'
    // 1. Actualiza el plugin a una versión compatible con Minecraft 26.2
    id 'net.neoforged.moddev' version '2.0.141' 
}

version = '1.0.0'
group = 'com.valhyi.recyclertable'

base {
    archivesName = 'recyclertable'
}

// 2. Cambia la versión de Java de 21 a 25 (Requerido por Minecraft 26.2+)
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = '26.2.0.70'

    runs {
        client {
            client()
        }
    }

    mods {
        recyclertable {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
    mavenCentral()
}

dependencies {
}
